  CREATE TABLE clientes(id INT PRIMARY KEY AUTO_INCREMENT, 
    nome VARCHAR(250),
	cpf VARCHAR(50),
	email VARCHAR(150),
	cep VARCHAR(25),
	tipo_logradouro VARCHAR(5),
	lougradouro VARCHAR(100),
	numero int,
	complemento VARCHAR(100),
	bairro VARCHAR(100),
	cidade VARCHAR(100),
	estado VARCHAR(100));